name: Create Windows Executable

on:
  push:
    tags:
      - 'v*.*.*'  # This pattern matches tags like 'v1.0.3'

jobs:
  build:
    runs-on: windows-latest  # Use the latest Windows runner
    permissions:
      contents: write  # Needed to create and upload releases
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Check out the code from the repository

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Specify the Python version (must include distutils module)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Build executable with PyInstaller
        run: |
          VERSION=$(echo "${GITHUB_REF#refs/tags/v}")
          pyinstaller --onefile tableau-workbook-extractor.py
          # Add the version number to the output executable
          EXE_NAME="tableau-workbook-extractor-${VERSION}.exe"
          mv dist/tableau-workbook-extractor dist/$EXE_NAME

      - name: Upload release
        uses: ncipollo/release-action@v1
        with:
          # tag: ${{ github.ref }}  # Use the tag from the workflow
          artifacts: dist/tableau-workbook-extractor.exe # Path to the executable to upload
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the built-in GITHUB_TOKEN
