name: Deploy Application

on:
  push:
    tags:
      - 'v*.*.*'  # This pattern matches tags like 'v1.0.3'

jobs:
  build-exe:
    runs-on: windows-latest  # Use latest Windows runner to create Windows executable
    permissions:
      contents: write  # Needed to create and upload releases
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Check out code from the repository

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Use downgraded Python version (must include distutils module)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r app/requirements.txt  # Install dependencies from requirements.txt

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile app/cli_main.py
          # Extract version number and add it to the output executable
          $tag = "${env:GITHUB_REF}"
          $version = $tag -replace 'refs/tags/', ''
          $exeName = "tableau-workbook-extractor-$version.exe"
          Rename-Item -Path dist\cli_main.exe -NewName $exeName
          # Make exe file name and version available for the next step as well
          echo "EXE_NAME=$exeName" >> $env:GITHUB_ENV
          echo "VERSION=$version" >> $env:GITHUB_ENV

      - name: Upload release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/${{env.EXE_NAME}} # Path to the executable to upload
          token: ${{secrets.GITHUB_TOKEN}}  # Use the built-in GITHUB_TOKEN
          allowUpdates: true # Update a release if it already exists
  deploy-flask:
    runs-on: ubuntu-latest  # The job will run on the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Check out the code from the repository

    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}  # API key for Render, stored in GitHub Secrets
        RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }} # Render app service ID
      run: |
        # Authenticate with Render API
        curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{"branch": "main"}'  # Trigger deployment for the main branch
