name: Create Windows Executable

on:
  push:
    tags:
      - 'v*.*.*'  # This pattern matches tags like 'v1.0.3'
    branches:
      - 'main' # Tag is pushed on main branch

jobs:
  build:
    runs-on: windows-latest  # Use latest Windows runner to create Windows executable
    permissions:
      contents: write  # Needed to create and upload releases
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Check out code from the repository

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Use downgraded Python version (must include distutils module)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile tableau-workbook-extractor.py
          # Extract version number and add it to the output executable
          $tag = "${env:GITHUB_REF}"
          $version = $tag -replace 'refs/tags/', ''
          $exeName = "tableau-workbook-extractor-$version.exe"
          Rename-Item -Path dist\tableau-workbook-extractor.exe -NewName $exeName
          # Make exe file name available for the next step as well
          echo "EXE_NAME=$exeName" >> $env:GITHUB_ENV

      - name: Upload release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/${{env.EXE_NAME}} # Path to the executable to upload
          token: ${{secrets.GITHUB_TOKEN}}  # Use the built-in GITHUB_TOKEN
