name: Create Windows Executable

on:
  push:
    tags:
      - 'v*.*.*'  # This pattern matches tags like 'v1.0.3'

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Check out the code from the repository

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Specify the Python version (must include distutils module)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Build executable
        run: |
          pyinstaller --onefile tableau-workbook-extractor.py  # Build the executable

      - name: Upload release
        uses: ncipollo/release-action@v1
        with:
          files: dist/tableau-workbook-extractor.exe  # Path to the executable to upload
